apiVersion: v1  # Core API version for Service objects
kind: Service   # Defines this as a Kubernetes Service

metadata:
  name: products-db  # Name of the service (used for internal DNS)
  labels:
    kubernetes.courselabs.co: hackathon  # Label for tracking in the hackathon
    app: widgetario                      # App label for service grouping

spec:
  ports:
    - port: 5432              # Port exposed by the service inside the cluster
      targetPort: postgres    # Maps to the named port in the database container

  selector:
    app: widgetario
    component: products-db    # Selects Pods with these labels to route traffic to

  type: ClusterIP             # Default service type; accessible only within the cluster

