apiVersion: v1  # Defines this as a core Kubernetes Service resource
kind: Service   # Specifies that this manifest creates a Service

metadata:
  name: products-api  # The name of the Service (used by other components to connect)
  labels:
    app: widgetario    # Labels used for grouping and selection

spec:
  selector:
    app: widgetario
    component: products-api  # Targets the Pods with these matching labels

  ports:
    - protocol: TCP          # Communication protocol
      port: 80               # Port exposed by the Service (inside the cluster)
      targetPort: http       # Refers to the named container port in the Deployment

  type: ClusterIP            # Default type; exposes the service on a stable internal IP

