apiVersion: v1  # Core API group for basic Kubernetes objects
kind: Secret    # Declares a Secret to store sensitive data like credentials

metadata:
  name: products-api-db  # Name used to reference this secret in other resources
  labels:
    kubernetes.courselabs.co: hackathon  # Label for hackathon identification/tracking

type: Opaque  # Generic secret type (base64-encoded string data)

stringData:
  application.properties: |-  # Plain text content will be stored as a file inside the container
    spring.jpa.database=POSTGRESQL
    spring.datasource.platform=postgres
    spring.datasource.url=jdbc:postgresql://products-db:5432/postgres
    spring.datasource.username=postgres
    spring.datasource.password=h4ckkath0n

