apiVersion: v1
kind: Secret  # This secret stores configuration data for the web frontend
metadata:
  name: web-api  # Name used to reference this secret in a Deployment (e.g., for volume mount)
  labels:
    kubernetes.courselabs.co: hackathon  # Helps organize resources specific to the hackathon

type: Opaque  # Indicates it's a generic secret (default for user-defined key-value data)

stringData:
  api.json: |-  # JSON config file embedded directly in the secret (will be mounted as a file)
    {
      "Widgetario": {
        "ProductsApi": {
          "Url": "http://products-api.default.svc.cluster.local/products"
        },
        "StockApi": {
          "Url": "http://stock-api.default.svc.cluster.local/stock"
        }
      }
    }

